print("Welcome to Band Name Generator!")
print("What's the name of the city you grew up in?")
city = input()
print("What's your pet's name?")
petname = input()
print("Your band name could be", city, petname)